video_path: "videos/example.mp4"
image_transform:
  vertical_flip: False
  horizontal_flip: False
  debug: True
perspective_transform:
  src: [[260, 240], [380, 240], [600, 335], [40, 335]]
  dst: [[220, 0], [420, 0], [420, 340], [220, 340]]
  vertical_flip: False
  horizontal_flip: False
  debug: True
lane_detector:
  model_path: "pretrained/best.pth"
  video_path: "videos/lane_detector/example.mp4"
  save_video: False
  debug: True
lane_fitting:
  contours:
    min_area: 800
    max_area: 2000
  lane:
    max_width: 100
    max_lanes: 4
  window:
    height: 40
    width: 60
    margin_x: 20
    min_pixels: 50
    max_pixels: 4500
  debug: True
lane_tracking:
  center_dist: 70