video_path: "videos/example.mp4"
lane_detector:
  model_path: "pretrained/best.pth"
  debug: True
lane_fitting:
  contours:
    min_area: 800
    max_area: 2000
  roi:
    height: 0.5
  debug: True
lane_tracking:
  debug: True
