video_path: "videos/turtlebot.mp4"
image_transform:
  vertical_flip: False
  horizontal_flip: False
  debug: True
perspective_transform:
  src: [[190, 200], [410, 200], [640, 360], [0, 360]]
  dst: [[240, 0], [400, 0], [400, 360], [240, 360]]
  vertical_flip: True
  horizontal_flip: True
  debug: True
lane_detector:
  model_path: "pretrained/best.pth"
  debug: True
lane_fitting:
  contours:
    min_area: 800
    max_area: 2000
  lane:
    max_width: 100
  window:
    height: 30
    width: 70
    margin_x: 30
    min_pixels: 50
    max_pixels: 4500
  histogram:
    height_ratio: 0.7
    seed: 64
  debug: True
lane_tracking:
  debug: True